import tkinter as tk
import tkinter.font as tkFont

root = tk.Tk()
font = tkFont.Font(family="Arial", size=12)
font2 = tkFont.Font(family="Helvetica", size=12)
font3 = tkFont.Font(family="Courier", size=12)
font4 = tkFont.Font(family="Verdana", size=12)
font5 = tkFont.Font(family="Georgia", size=12)
font6 = tkFont.Font(family="Comic Sans MS", size=12)
font7 = tkFont.Font(family="Trebuchet MS", size=12)
font8 = tkFont.Font(family="Arial Narrow", size=12)
font9 = tkFont.Font(family="Arial Black", size=12)
font10 = tkFont.Font(family="Impact", size=12)
font11 = tkFont.Font(family="Bookman Old Style", size=12)
font12 = tkFont.Font(family="Consolas", size=12)
font13 = tkFont.Font(family="Lucida Console", size=12)
font14 = tkFont.Font(family="Lucida Sans Unicode", size=12)
font15 = tkFont.Font(family="Microsoft Sans Serif", size=12)
font16 = tkFont.Font(family="Symbol", size=12)
font17 = tkFont.Font(family="System", size=12)
font18 = tkFont.Font(family="Times New Roman", size=12)
font19 = tkFont.Font(family="Webdings", size=12)
font20 = tkFont.Font(family="Wingdings", size=12)
font21 = tkFont.Font(family="MS Sans Serif", size=12)
font22 = tkFont.Font(family="MS Serif", size=12)

label = tk.Label(root, text="Arial", font=font)
label1 = tk.Label(root, text="Helvetica", font=font2)
label2 = tk.Label(root, text="Courier", font=font3)
label3 = tk.Label(root, text="Verdana", font=font4)
label4 = tk.Label(root, text="Georgia", font=font5)
label5 = tk.Label(root, text="Comic Sans MS", font=font6)
label6 = tk.Label(root, text="Trebuchet MS", font=font7)
label7 = tk.Label(root, text="Arial Narrow", font=font8)
label8 = tk.Label(root, text="Arial Black", font=font9)
label9 = tk.Label(root, text="Impact", font=font10)
label10 = tk.Label(root, text="Bookman Old Style", font=font11)
label11 = tk.Label(root, text="Consolas", font=font12)
label12 = tk.Label(root, text="Lucida Console", font=font13)
label13 = tk.Label(root, text="Lucida Sans Unicode", font=font14)
label14 = tk.Label(root, text="Microsoft Sans Serif", font=font15)
label15 = tk.Label(root, text="Symbol", font=font16)
label16 = tk.Label(root, text="System", font=font17)
label17 = tk.Label(root, text="Times New Roman", font=font18)
label18 = tk.Label(root, text="Webdings", font=font19)
label19 = tk.Label(root, text="Wingdings", font=font20)
label20 = tk.Label(root, text="MS Sans Serif", font=font21)
label21 = tk.Label(root, text="MS Serif", font=font22)

label.pack()
label1.pack()
label2.pack()
label3.pack()
label4.pack()
label5.pack()
label6.pack()
label7.pack()
label8.pack()
label9.pack()
label10.pack()
label11.pack()
label12.pack()
label13.pack()
label14.pack()
label15.pack()
label16.pack()
label17.pack()
label18.pack()
label19.pack()
label20.pack()
label21.pack()

root.mainloop()